baseURL: https://sgswtky.github.io/
footnoteReturnLinkContents: ↩
title: 壁は登るためにある
languageCode: ja-jp
publishDir: public
theme: hugo-lithium-theme
hasCJKLanguage: true
pygmentsCodefences: true
pygmentsStyle: native

menu:
  main:
    - name: Blog
      url: /
    - name: About
      url: /about/
    - name: GitHub
      url: https://github.com/sgswtky
    - name: Twitter
      url: https://twitter.com/sgswtky

params:
  description: "sgswtkyのブログ"
  logo:
    url: logo.png
    width: 50
    height: 50
    alt: logo
  addThis: ra-5b4b66137935d0b4
